services:
  - type: web
    name: aviflux-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python dynamic_route_backend.py"
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production

  - type: web
    name: aviflux-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: frontend/dist
    plan: starter
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://aviflux-backend.onrender.com